export const skillsStack = [
  {name: 'JavaScript', url: '../../../assets/logos/javascript.svg', rate: 10, delay: '200', animation: 'zoom-in', offset: '200'},
  {name: 'TypeScript', url: '../../../assets/logos/typescript.svg', rate: 8, delay: '250', animation: 'zoom-in', offset: '200'},
  {name: 'Angular', url: '../../../assets/logos/angular.svg', rate: 8, delay: '300', animation: 'zoom-in', offset: '200'},
  {name: 'ReactJS', url: '../../../assets/logos/reactjs.svg', rate: 7, delay: '350', animation: 'zoom-in', offset: '200'},
  {name: 'HTML5', url: '../../../assets/logos/html5.svg', rate: 10, delay: '400', animation: 'zoom-in', offset: '200'},
  {name: 'CSS3', url: '../../../assets/logos/css3.svg', rate: 10, delay: '450', animation: 'zoom-in', offset: '200'},
  {name: 'SASS/SCSS', url: '../../../assets/logos/sassscss.svg', rate: 9, delay: '500', animation: 'zoom-in', offset: '200'},
  {name: 'SCRUM', url: '../../../assets/logos/scrum.svg', rate: 10, delay: '550', animation: 'zoom-in', offset: '200'},
  {name: 'API', url: '../../../assets/logos/api.png', rate: 8, delay: '600', animation: 'zoom-in', offset: '200'},
  {name: 'REST', url: '../../../assets/logos/rest.svg', rate: 8, delay: '650', animation: 'zoom-in', offset: '200'},
  {name: 'Firebase', url: '../../../assets/logos/firebase.svg', rate: 7, delay: '750', animation: 'zoom-in', offset: '200'},
  {name: 'Git', url: '../../../assets/logos/git.png', rate: 10, delay: '800', animation: 'zoom-in', offset: '200'},
  {name: 'Github', url: '../../../assets/logos/github.svg', rate: 10, delay: '850', animation: 'zoom-in', offset: '200'},
  {name: 'PHP', url: '../../../assets/logos/php.svg', rate: 6, delay: '900', animation: 'zoom-in', offset: '200'},
];
