export const skillsStack = [
  {name: 'JavaScript', url: '../../../assets/logos/javascript.svg', rate: 10},
  {name: 'TypeScript', url: '../../../assets/logos/typescript.svg', rate: 8},
  {name: 'Angular', url: '../../../assets/logos/angular.svg', rate: 8},
  {name: 'ReactJS', url: '../../../assets/logos/reactjs.svg', rate: 7},
  {name: 'HTML5', url: '../../../assets/logos/html5.svg', rate: 10},
  {name: 'CSS3', url: '../../../assets/logos/css3.svg', rate: 10},
  {name: 'SASS/SCSS', url: '../../../assets/logos/sassscss.svg', rate: 9},
  {name: 'SCRUM', url: '../../../assets/logos/scrum.svg', rate: 10},
  {name: 'API', url: '../../../assets/logos/api.png', rate: 8},
  {name: 'REST', url: '../../../assets/logos/rest.svg', rate: 8},
  {name: 'Firebase', url: '../../../assets/logos/firebase_logo.svg', rate: 7},
  {name: 'Git', url: '../../../assets/logos/git.png', rate: 10},
  {name: 'Github', url: '../../../assets/logos/github.svg', rate: 10},
  {name: 'PHP', url: '../../../assets/logos/php.svg', rate: 6},
];
