export const skillsStack = [
  {name: 'JavaScript', url: '../../../assets/logos/javascript.svg', animation: 'zoom-in'},
  {name: 'TypeScript', url: '../../../assets/logos/typescript.svg', animation: 'zoom-in'},
  {name: 'Angular', url: '../../../assets/logos/angular.svg', animation: 'zoom-in'},
  {name: 'ReactJS', url: '../../../assets/logos/reactjs.svg', animation: 'zoom-in'},
  {name: 'Python', url: '../../../assets/logos/python.svg', animation: 'zoom-in'},
  {name: 'Django', url: '../../../assets/logos/django.svg', animation: 'zoom-in'},
  {name: 'HTML5', url: '../../../assets/logos/html5.svg', animation: 'zoom-in'},
  {name: 'CSS3', url: '../../../assets/logos/css3.svg', animation: 'zoom-in'},
  {name: 'SASS/SCSS', url: '../../../assets/logos/sassscss.svg', animation: 'zoom-in'},
  {name: 'SCRUM', url: '../../../assets/logos/scrum.svg', animation: 'zoom-in'},
  {name: 'API', url: '../../../assets/logos/api.png', animation: 'zoom-in'},
  {name: 'REST', url: '../../../assets/logos/rest.svg', animation: 'zoom-in'},
  {name: 'Firebase', url: '../../../assets/logos/firebase.svg', animation: 'zoom-in'},
  {name: 'SQL', url: '../../../assets/logos/sql.svg', animation: 'zoom-in'},
  {name: 'Docker', url: '../../../assets/logos/docker.svg', animation: 'zoom-in'},
  {name: 'Git', url: '../../../assets/logos/git.png', animation: 'zoom-in'},
  {name: 'Github', url: '../../../assets/logos/github.svg', animation: 'zoom-in'},
  {name: 'PHP', url: '../../../assets/logos/php.svg', animation: 'zoom-in'},
];
